version: 1.0.{build}

environment:
  nuget_api_key:
    secure: kM3Kse+ivuuE5RVoe6dPdw+aguWx56K2YeXujGa9tMPQTms3lv7QxNpTLFMALYNa
      
install:
  - cinst stylecop
  - cinst LynxToolkit
  
platform: Any CPU

configuration: Release

build:
  project: Source/QuantityTypes.sln
  verbosity: normal

before_build:
  - cmd: UpdateVersionNumbers /Version=%APPVEYOR_BUILD_VERSION% /Dependency=QuantityTypes /ReleaseNotesFile=release-notes.txt /Directory=Source
  
deploy_script:
  - cmd: mkdir Packages
  - cmd: NuGet pack Source\QuantityTypes\QuantityTypes.nuspec -OutputDirectory Packages
  - cmd: for %%G in (Packages\*.nupkg) do NuGet push %%G %nuget_api_key%
artifacts:
  - path: Output
    name: QuantityTypes-$(APPVEYOR_BUILD_VERSION)
    type: zip
